# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/blog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core/blog.proto',
  package='core',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x63ore/blog.proto\x12\x04\x63ore\"E\n\x04\x42log\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tauthor_id\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"\x11\n\x0fListBlogRequest\",\n\x10ListBlogResponse\x12\x18\n\x04\x62log\x18\x01 \x01(\x0b\x32\n.core.Blog2J\n\x0b\x42logService\x12;\n\x08ListBlog\x12\x15.core.ListBlogRequest\x1a\x16.core.ListBlogResponse0\x01\x62\x06proto3'
)




_BLOG = _descriptor.Descriptor(
  name='Blog',
  full_name='core.Blog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='core.Blog.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author_id', full_name='core.Blog.author_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='core.Blog.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='core.Blog.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=94,
)


_LISTBLOGREQUEST = _descriptor.Descriptor(
  name='ListBlogRequest',
  full_name='core.ListBlogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=113,
)


_LISTBLOGRESPONSE = _descriptor.Descriptor(
  name='ListBlogResponse',
  full_name='core.ListBlogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blog', full_name='core.ListBlogResponse.blog', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=159,
)

_LISTBLOGRESPONSE.fields_by_name['blog'].message_type = _BLOG
DESCRIPTOR.message_types_by_name['Blog'] = _BLOG
DESCRIPTOR.message_types_by_name['ListBlogRequest'] = _LISTBLOGREQUEST
DESCRIPTOR.message_types_by_name['ListBlogResponse'] = _LISTBLOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blog = _reflection.GeneratedProtocolMessageType('Blog', (_message.Message,), {
  'DESCRIPTOR' : _BLOG,
  '__module__' : 'core.blog_pb2'
  # @@protoc_insertion_point(class_scope:core.Blog)
  })
_sym_db.RegisterMessage(Blog)

ListBlogRequest = _reflection.GeneratedProtocolMessageType('ListBlogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOGREQUEST,
  '__module__' : 'core.blog_pb2'
  # @@protoc_insertion_point(class_scope:core.ListBlogRequest)
  })
_sym_db.RegisterMessage(ListBlogRequest)

ListBlogResponse = _reflection.GeneratedProtocolMessageType('ListBlogResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTBLOGRESPONSE,
  '__module__' : 'core.blog_pb2'
  # @@protoc_insertion_point(class_scope:core.ListBlogResponse)
  })
_sym_db.RegisterMessage(ListBlogResponse)



_BLOGSERVICE = _descriptor.ServiceDescriptor(
  name='BlogService',
  full_name='core.BlogService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=161,
  serialized_end=235,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListBlog',
    full_name='core.BlogService.ListBlog',
    index=0,
    containing_service=None,
    input_type=_LISTBLOGREQUEST,
    output_type=_LISTBLOGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOGSERVICE)

DESCRIPTOR.services_by_name['BlogService'] = _BLOGSERVICE

# @@protoc_insertion_point(module_scope)
