# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from core import blog_pb2 as core_dot_blog__pb2


class BlogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBlog = channel.unary_stream(
                '/core.BlogService/ListBlog',
                request_serializer=core_dot_blog__pb2.ListBlogRequest.SerializeToString,
                response_deserializer=core_dot_blog__pb2.ListBlogResponse.FromString,
                )


class BlogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBlog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBlog': grpc.unary_stream_rpc_method_handler(
                    servicer.ListBlog,
                    request_deserializer=core_dot_blog__pb2.ListBlogRequest.FromString,
                    response_serializer=core_dot_blog__pb2.ListBlogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.BlogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBlog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/core.BlogService/ListBlog',
            core_dot_blog__pb2.ListBlogRequest.SerializeToString,
            core_dot_blog__pb2.ListBlogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
