version: "3"

services:
    db:
        image: "mysql" # use latest official MySQL version
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        volumes:
            - mysql-data:/var/lib/mysql # persist data even if container shuts down

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "testtopic:3:1"
        depends_on:
            - zookeeper

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - LOCALHOST=docker.for.mac.localhost
        ports:
            - "8000:8000"
        volumes:
            - .:/app # mount the current dir to /app dir in the container (so that when any changes made locally will be reflected in the container)
        depends_on:
            - db
            - kafka

volumes:
    mysql-data: # named volumes can be managed easier using docker-compose
