version: "3"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app # mount the current dir to /app dir in the container (so that when any changes made locally will be reflected in the container)

    db:
        image: "mysql" # use latest official MySQL version
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        volumes:
            - mysql-data:/var/lib/mysql # persist data even if container shuts down

volumes:
    mysql-data: # named volumes can be managed easier using docker-compose
